BASE_DIR: /srv/mirror

# Any path under this must be in relative of BASE_DIR.
# Script doesnt do any kind of outbound check, so make sure to check all paths.

global:
  scripts:
    pre:
    post:
  log: logs/sync.log
  sync:
    - ALL

defaults:
  type: rsync
  scripts:
    pre:
    fail:
      - scripts/alert.sh
    post:
      - scripts/index.py
  log: logs/${path}.log
  rsync:
    options: "-rtlHpv --chmod=D0755,F0644 --partial --hard-links --safe-links --stats --delete --delete-after --delay-updates --max-delete=70000"
    exclude:
      - ".*.??????"
      - ".~tmp~/"
      - "Packages*"
      - "Sources*"
      - "Release*"
      - "*.links.tar.gz*"
      - "/other"
      - "/sources"

repos:
  ARCHLINUX:
    url: rsync://mirrors.xtom.de/archlinux/
    delay: 4
    name: "ArchLinux (x86_64)"
    path: archlinux

  UBUNTU:
    url: rsync://rsync.archive.ubuntu.com/ubuntu/
    delay: 4
    name: "Ubuntu"
    path: ubuntu

  UBUNTU_CD:
    url: rsync://releases.ubuntu.com/releases/
    delay: 12
    name: "Ubuntu Releases"
    path: ubuntu_cd

  UBUNTU_CD_OLD:
    url: rsync://old-releases.ubuntu.com/releases/
    delay: 12
    name: "Ubuntu Releases (Old)"
    path: ubuntu_cd_old

  DEBIAN:
    url: rsync://mirrors.xtom.jp/debian/
    type: ftpsync
    delay: 4
    name: Debian
    path: debian
    scripts:
    # pre: scripts/pre_debian.sh
    last_sync: "2023-10-12T10:58Z"
  
  DEBIAN_CD:
    url: rsync://ftp.lanet.kr/debian-cd/
    delay: 12
    name: "Debian CD"
    path: debian_cd
  
  FEDORA:
    url: rsync://dl.fedoraproject.org/fedora-enchilada/linux/
    delay: 4
    name: "Fedora"
    path: fedora
  
  RASPBIAN:
    url: rsync://archive.raspbian.org/archive/
    delay: 6
    name: "Raspbian"
    path: raspbian
  
  MANJARO:
    url: rsync://ftp.riken.jp/manjaro/
    delay: 4
    name: Manjaro
    path: manjaro
  
  ARCHLINUXARM:
    name: "ArchLinux (ARM)"
    path: archlinuxarm
    url: http://jp.mirror.archlinuxarm.org/
    type: http
    delay: 12
  
  ASAHILINUX:
    name: "AsahiLinux"
    path: asahilinux
    url: https://cdn.asahilinux.org/
    type: http
    delay: 12

index:
  - ARCHLINUX
  - UBUNTU UBUNTU_CD
  - DEBIAN DEBIAN_CD
  - FEDORA
  - MANJARO
  - RASPBIAN
  - DIVIDER
  - ARCHLINUXARM
  - ASAHILINUX
  - UBUNTU_CD_OLD