BASE_DIR: /srv/mirror
ENV: ./scripts/.env
global:
  type: rsync
  scripts:
    pre:
    # - ./scripts/cleanup.sh
    fail:
      - ./scripts/alert.sh
    post:
      - ./script/index.py
    # - ./script/rotate_log.py
  log: ./logs/sync.log
  log_dir: ./logs/
  sync:
    - ALL
  rsync:
    options: "-rtlHpv --chmod=D0755,F0644 --partial --hard-links --safe-links --stats --delete --delete-after --delay-updates --max-delete=70000"
    exclude:
      - ".*.??????"
      - ".~tmp~/"
      - "Packages*"
      - "Sources*"
      - "Release*"
      - "*.links.tar.gz*"
      - "/other"
      - "/sources"
repos:
  ARCHLINUX:
    url: rsync://mirrors.xtom.de/archlinux/
    duration: 4
    name: "ArchLinux (x86_64)"
    path: archlinux
    log: ./logs/archlinux
    last_sync: "2023-10-09T23:48Z"
  UBUNTU:
    url: rsync://rsync.archive.ubuntu.com/ubuntu/
    duration: 4
    name: "Ubuntu"
    path: ubuntu
    log: ./logs/ubuntu
    last_sync: "2023-10-09T23:48Z"
  UBUNTU_CD:
    url: rsync://releases.ubuntu.com/releases/
    duration: 24
    name: "Ubuntu Releases"
    path: ubuntu_cd
    log: ./logs/ubuntu_cd
    last_sync: "2023-10-09T23:48Z"
  UBUNTU_CD_OLD:
    url: rsync://old-releases.ubuntu.com/releases/
    duration: 24
    name: "Ubuntu Releases (Old)"
    path: ubuntu_cd_old
    log: ./logs/ubuntu_cd_old
    last_sync: "2023-10-09T23:48Z"
  DEBIAN:
    url: rsync://mirrors.xtom.jp/debian/
    type: ftpsync
    duration: 4
    name: Debian
    path: debian
    scripts:
    # pre: ./scripts/pre_debian.sh
    last_sync: "2023-10-09T23:48Z"
  DEBIAN_CD:
    url: rsync://ftp.lanet.kr/debian-cd/
    duration: 24
    name: "Debian CD"
    path: debian_cd
    log: ./logs/debian_cd
    last_sync: "2023-10-09T23:48Z"
  FEDORA:
    url: rsync://dl.fedoraproject.org/fedora-enchilada/linux/
    duration: 4
    name: "Fedora"
    path: fedora
    log: ./logs/fedora
    last_sync: "2023-10-09T23:30Z"
  RASPBIAN:
    url: rsync://archive.raspbian.org/archive/
    duration: 6
    name: "Raspbian"
    path: raspbian
    log: ./logs/raspbian
    last_sync: "2023-10-09T23:30Z"
  MANJARO:
    url: rsync://ftp.riken.jp/manjaro/
    duration: 4
    name: Manjaro
    path: manjaro
    log: ./logs/manjaro
    last_sync: "2023-10-09T23:30Z"
  ARCHLINUXARM:
    name: "ArchLinux (ARM)"
    path: archlinuxarm
    url: http://jp.mirror.archlinuxarm.org/
    type: http
    duration: 12
    last_sync: "2023-10-09T23:30Z"
  ASAHILINUX:
    name: "AsahiLinux"
    path: asahilinux
    url: https://cdn.asahilinux.org/
    type: http
    duration: 12
    last_sync: "2023-10-09T23:30Z"
index:
  - ARCHLINUX
  - UBUNTU UBUNTU_CD
  - DEBIAN DEBIAN_CD
  - FEDORA
  - MANJARO
  - RASPBIAN
  - DIVIDER
  - ARCHLINUXARM
  - ASAHILINUX
  - UBUNTU_CD_OLD
